### ISSUE TITLE
Problem associating logfiles with the artdaq processes

### ISSUE THREAD

**Issue by gennadiy-fnal** [art-daq/artdaq_daqinterface#6]
Determining logfiles associated with the artdaq processes...
Problem associating logfiles with the artdaq processes. Output is as follows:

STDOUT:
======================================================================

======================================================================

Traceback (most recent call last):
  File "/daq/software/products/artdaq_daqinterface/v3_11_02/rc/control/daqinterface.py", line 2192, in do_boot
    self.get_artdaq_log_filenames()
  File "/daq/software/products/artdaq_daqinterface/v3_11_02/rc/control/daqinterface.py", line 1246, in get_artdaq_log_filenames
    self.print_log("e", "STDERR:\n======================================================================\n%s\n======================================================================\n" % ("".join(procline
s_err)))
TypeError: sequence item 0: expected str instance, bytes found

Wed Jul 20 11:09:56 CDT 2022: RECOVER transition underway
Wed Jul 20 11:09:56 CDT 2022: Attempting to cleanly wind down the BoardReaders if they (still) exist

Unable to determine state of artdaq process spectdc at
sbnd-clk01-daq:13100; will not be able to complete its stop-and-shutdown

**Comment by VCLanNguyen** [comment]
PR for the fix: https://github.com/art-daq/artdaq_daqinterface/pull/7
